#!/usr/bin/env python3
"""Build static frontend for CDN hosting (GitHub Pages / Cloudflare Pages).

Copies ``webapp/static/`` into ``dist/`` with ``index.html`` at the root,
relative asset paths, and a production ``js/config.js`` pointing at the Fly.io API.

Usage::

    python scripts/build_static.py
    python scripts/build_static.py --api-base https://coh-ucs-tools.fly.dev --out dist
    python scripts/build_static.py --site-url https://benmed00.github.io/coh-ucs-tools
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
STATIC_SRC = ROOT / "webapp" / "static"
DEFAULT_API_BASE = "https://coh-ucs-tools.fly.dev"
DEFAULT_SITE_URL = "https://benmed00.github.io/coh-ucs-tools"

# Map /static/... URLs in source to relative paths in dist/.
_PATH_REWRITES = (
    ("/static/css/", "./css/"),
    ("/static/js/", "./js/"),
    ("/static/fonts/", "./fonts/"),
    ("/static/i18n/", "./i18n/"),
    ("/static/icons/", "./icons/"),
    ("/static/manifest.json", "./manifest.json"),
    ("/static/service-worker.js", "./service-worker.js"),
)

_SW_CACHE = "coh-ucs-v4"

# Service-worker cache list uses absolute /static/ paths in source.
_SW_ASSETS = (
    "/",
    "./css/fonts.css",
    "./css/app.css",
    "./js/config.js",
    "./js/router.js",
    "./js/seo.js",
    "./js/app.js",
    "./js/core.js",
    "./js/features.js",
    "./js/hero.js",
    "./manifest.json",
    "./icons/favicon.svg",
    "./icons/icon-192.png",
    "./icons/apple-touch-icon.png",
    "./icons/og-image.png",
    "./fonts/inter-400-latin.woff2",
    "./fonts/inter-500-latin.woff2",
    "./i18n/en.json",
    "./i18n/fr.json",
    "./i18n/ar.json",
)


def _rewrite_static_paths(text: str) -> str:
    for old, new in _PATH_REWRITES:
        text = text.replace(old, new)
    return text


def _rewrite_site_url(text: str, site_url: str) -> str:
    """Replace canonical UI URLs when static deploy uses a different origin."""
    origin = site_url.rstrip("/")
    text = text.replace("https://benmed00.github.io/coh-ucs-tools", origin)
    return text


def _write_config_js(dest: Path, api_base: str, site_url: str, base_path: str) -> None:
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(
        "// Generated by scripts/build_static.py — do not edit in dist/.\n"
        f'window.API_BASE = "{api_base}";\n'
        f'window.SITE_URL = "{site_url.rstrip("/")}";\n'
        f'window.BASE_PATH = "{base_path}";\n',
        encoding="utf-8",
    )


def _write_service_worker(dest: Path) -> None:
    assets = ",\n  ".join(f'"{a}"' for a in _SW_ASSETS)
    dest.write_text(
        f'const CACHE = "{_SW_CACHE}";\n'
        f"const ASSETS = [\n  {assets},\n];\n\n"
        f'self.addEventListener("install", (e) => {{\n'
        f"  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(ASSETS)).then(() => self.skipWaiting()));\n"
        f"}});\n\n"
        f'self.addEventListener("activate", (e) => {{\n'
        f"  e.waitUntil(\n"
        f"    caches.keys().then((keys) =>\n"
        f"      Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)))\n"
        f"    ).then(() => self.clients.claim())\n"
        f"  );\n"
        f"}});\n\n"
        f'self.addEventListener("fetch", (e) => {{\n'
        f"  if (!e.request.url.startsWith(self.location.origin)) return;\n"
        f'  if (e.request.url.includes("/api/")) return;\n'
        f"  e.respondWith(\n"
        f"    caches.match(e.request).then((cached) =>\n"
        f"      cached || fetch(e.request).then((res) => {{\n"
        f'        if (res.ok && e.request.method === "GET") {{\n'
        f"          const clone = res.clone();\n"
        f"          caches.open(CACHE).then((c) => c.put(e.request, clone));\n"
        f"        }}\n"
        f"        return res;\n"
        f"      }}).catch(() => caches.match(\"./\"))\n"
        f"    )\n"
        f"  );\n"
        f"}});\n",
        encoding="utf-8",
    )


def _write_manifest(dest: Path) -> None:
    src = STATIC_SRC / "manifest.json"
    data = json.loads(src.read_text(encoding="utf-8"))
    data["start_url"] = "./"
    data["scope"] = "./"
    for icon in data.get("icons", []):
        icon["src"] = icon["src"].replace("/static/icons/", "./icons/")
    dest.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")


def _write_robots(dest: Path, site_url: str) -> None:
    from webapp.seo import robots_txt

    dest.write_text(robots_txt(sitemap_url=f"{site_url.rstrip('/')}/sitemap.xml"), encoding="utf-8")


def _write_sitemap(dest: Path, site_url: str) -> None:
    from webapp.seo import sitemap_xml

    dest.write_text(
        sitemap_xml(base_url=site_url.rstrip("/"), include_api_docs=False),
        encoding="utf-8",
    )


def _write_headers(dest: Path) -> None:
    """Cloudflare Pages / compatible CDN cache rules."""
    dest.write_text(
        "/fonts/*\n"
        "  Cache-Control: public, max-age=31536000, immutable\n\n"
        "/css/*\n"
        "  Cache-Control: public, max-age=604800, immutable\n\n"
        "/js/*\n"
        "  Cache-Control: public, max-age=604800, immutable\n\n"
        "/icons/*\n"
        "  Cache-Control: public, max-age=604800, immutable\n\n"
        "/sitemap.xml\n"
        "  Cache-Control: public, max-age=3600\n\n"
        "/robots.txt\n"
        "  Cache-Control: public, max-age=3600\n",
        encoding="utf-8",
    )


def _write_indexnow_key(dest: Path) -> None:
    from webapp.seo import indexnow_key

    key = indexnow_key()
    if key:
        (dest / f"{key}.txt").write_text(key + "\n", encoding="utf-8")


def _base_path_for_site(site_url: str) -> str:
    from webapp.seo import GITHUB_PAGES_BASE_PATH

    if "github.io/" in site_url.rstrip("/") + "/":
        return GITHUB_PAGES_BASE_PATH
    return ""


def build_static(out_dir: Path, api_base: str, site_url: str) -> None:
    """Populate *out_dir* with a static CDN-ready frontend."""
    from webapp.seo import inject_index_html

    if out_dir.exists():
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True)

    for name in ("css", "js", "i18n", "icons", "fonts"):
        src = STATIC_SRC / name
        if src.is_dir():
            shutil.copytree(src, out_dir / name)

    base_path = _base_path_for_site(site_url)
    index_src = (STATIC_SRC / "index.html").read_text(encoding="utf-8")
    index_out = inject_index_html(index_src, base_url=site_url, base_path=base_path)
    index_out = _rewrite_static_paths(index_out)
    index_out = _rewrite_site_url(index_out, site_url)
    (out_dir / "index.html").write_text(index_out, encoding="utf-8")
    (out_dir / "404.html").write_text(index_out, encoding="utf-8")

    seo_dir = STATIC_SRC / "seo"
    if seo_dir.is_dir():
        for vf in seo_dir.glob("google*.html"):
            shutil.copy(vf, out_dir / vf.name)

    _write_config_js(out_dir / "js" / "config.js", api_base.rstrip("/"), site_url.rstrip("/"), base_path)
    _write_manifest(out_dir / "manifest.json")
    _write_service_worker(out_dir / "service-worker.js")
    _write_robots(out_dir / "robots.txt", site_url)
    _write_sitemap(out_dir / "sitemap.xml", site_url)
    _write_headers(out_dir / "_headers")
    _write_indexnow_key(out_dir)

    print(f"Built static UI -> {out_dir}")
    print(f"  API_BASE = {api_base.rstrip('/')}")
    print(f"  SITE_URL = {site_url.rstrip('/')}")
    print(f"  BASE_PATH = {base_path or '(root)'}")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Build static frontend for CDN deploy.")
    parser.add_argument(
        "--out",
        type=Path,
        default=ROOT / "dist",
        help="Output directory (default: dist/)",
    )
    parser.add_argument(
        "--api-base",
        default=DEFAULT_API_BASE,
        help=f"Fly.io API origin (default: {DEFAULT_API_BASE})",
    )
    parser.add_argument(
        "--site-url",
        default=DEFAULT_SITE_URL,
        help=f"Canonical static UI origin (default: {DEFAULT_SITE_URL})",
    )
    args = parser.parse_args(argv)
    api_base = args.api_base.rstrip("/")
    site_url = args.site_url.rstrip("/")
    if not re.match(r"^https?://", api_base):
        print("error: --api-base must be an http(s) URL", file=sys.stderr)
        return 1
    if not re.match(r"^https?://", site_url):
        print("error: --site-url must be an http(s) URL", file=sys.stderr)
        return 1
    build_static(args.out.resolve(), api_base, site_url)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
