#!/usr/bin/env python3
"""Build static frontend for CDN hosting (GitHub Pages / Cloudflare Pages).

Copies ``webapp/static/`` into ``dist/`` with ``index.html`` at the root,
relative asset paths, and a production ``js/config.js`` pointing at the Fly.io API.

Usage::

    python scripts/build_static.py
    python scripts/build_static.py --api-base https://coh-ucs-tools.fly.dev --out dist
"""

from __future__ import annotations

import argparse
import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
STATIC_SRC = ROOT / "webapp" / "static"
DEFAULT_API_BASE = "https://coh-ucs-tools.fly.dev"

# Map /static/... URLs in source to relative paths in dist/.
_PATH_REWRITES = (
    ("/static/css/", "./css/"),
    ("/static/js/", "./js/"),
    ("/static/i18n/", "./i18n/"),
    ("/static/manifest.json", "./manifest.json"),
    ("/static/service-worker.js", "./service-worker.js"),
)

# Service-worker cache list uses absolute /static/ paths in source.
_SW_ASSETS = (
    "/",
    "./css/app.css",
    "./js/config.js",
    "./js/app.js",
    "./js/core.js",
    "./js/features.js",
    "./js/hero.js",
    "./manifest.json",
    "./i18n/en.json",
    "./i18n/fr.json",
    "./i18n/ar.json",
)


def _rewrite_static_paths(text: str) -> str:
    for old, new in _PATH_REWRITES:
        text = text.replace(old, new)
    return text


def _write_config_js(dest: Path, api_base: str) -> None:
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(
        f'// Generated by scripts/build_static.py — do not edit in dist/.\n'
        f'window.API_BASE = "{api_base}";\n',
        encoding="utf-8",
    )


def _write_service_worker(dest: Path) -> None:
    assets = ",\n  ".join(f'"{a}"' for a in _SW_ASSETS)
    dest.write_text(
        f'const CACHE = "coh-ucs-v1";\n'
        f"const ASSETS = [\n  {assets},\n];\n\n"
        f"self.addEventListener(\"install\", (e) => {{\n"
        f"  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(ASSETS)).then(() => self.skipWaiting()));\n"
        f"}});\n\n"
        f"self.addEventListener(\"activate\", (e) => {{\n"
        f"  e.waitUntil(\n"
        f"    caches.keys().then((keys) =>\n"
        f"      Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)))\n"
        f"    ).then(() => self.clients.claim())\n"
        f"  );\n"
        f"}});\n\n"
        f"self.addEventListener(\"fetch\", (e) => {{\n"
        f"  if (!e.request.url.startsWith(self.location.origin)) return;\n"
        f"  if (e.request.url.includes(\"/api/\")) return;\n"
        f"  e.respondWith(\n"
        f"    caches.match(e.request).then((cached) =>\n"
        f"      cached || fetch(e.request).then((res) => {{\n"
        f"        if (res.ok && e.request.method === \"GET\") {{\n"
        f"          const clone = res.clone();\n"
        f"          caches.open(CACHE).then((c) => c.put(e.request, clone));\n"
        f"        }}\n"
        f"        return res;\n"
        f"      }}).catch(() => caches.match(\"./\"))\n"
        f"    )\n"
        f"  );\n"
        f"}});\n",
        encoding="utf-8",
    )


def _write_manifest(dest: Path) -> None:
    src = STATIC_SRC / "manifest.json"
    text = src.read_text(encoding="utf-8")
    text = text.replace('"start_url": "/"', '"start_url": "./"')
    dest.write_text(text, encoding="utf-8")


def build_static(out_dir: Path, api_base: str) -> None:
    """Populate *out_dir* with a static CDN-ready frontend."""
    if out_dir.exists():
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True)

    for name in ("css", "js", "i18n"):
        src = STATIC_SRC / name
        if src.is_dir():
            shutil.copytree(src, out_dir / name)

    index_src = (STATIC_SRC / "index.html").read_text(encoding="utf-8")
    index_out = _rewrite_static_paths(index_src)
    (out_dir / "index.html").write_text(index_out, encoding="utf-8")

    _write_config_js(out_dir / "js" / "config.js", api_base.rstrip("/"))
    _write_manifest(out_dir / "manifest.json")
    _write_service_worker(out_dir / "service-worker.js")

    print(f"Built static UI -> {out_dir}")
    print(f"  API_BASE = {api_base.rstrip('/')}")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Build static frontend for CDN deploy.")
    parser.add_argument(
        "--out",
        type=Path,
        default=ROOT / "dist",
        help="Output directory (default: dist/)",
    )
    parser.add_argument(
        "--api-base",
        default=DEFAULT_API_BASE,
        help=f"Fly.io API origin (default: {DEFAULT_API_BASE})",
    )
    args = parser.parse_args(argv)
    api_base = args.api_base.rstrip("/")
    if not re.match(r"^https?://", api_base):
        print("error: --api-base must be an http(s) URL", file=sys.stderr)
        return 1
    build_static(args.out.resolve(), api_base)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
